[package]
name = "lc-106-construct-binary-tree-from-inorder-and-postorder-traversal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leetcode_prelude = "0.2.3"
